#!/usr/bin/env python3

import sys

def factorize(num):
    factors = []
    for j in range(2, num):
        if num % j == 0:
            factors.append((j, num // j))
            break
    return factors

def main():
    filename = sys.argv[1]
    with open(filename, 'r') as file:
        numbers = file.readlines()
        for number in numbers:
            num = int(number.strip())
            factors = factorize(num)
            print(f"{num}={factors[0][0]}*{factors[0][1]}")

if __name__ == "__main__":
    main()
