#!/usr/bin/env python3

import sys
import math
import random
def gcd(a, b):
    while b != 0:
        a, b = b, a % b
    return a
def pollards_rho(n):
    x = random.randint(1, n - 1)
    y = x
    c = random.randint(1, n - 1)
    d = 1

    f = lambda x: (x**2 + c) % n

    while d == 1:
        x = f(x)
        y = f(f(y))
        d = gcd(abs(x - y), n)
    return d

def factorize_rsa_number(n):
    if n % 2 == 0:
        return f"{n}=2*{n // 2}"
    factor = pollards_rho(n)
    return f"{n}={factor}*{n // factor}"

def main(filename):
    with open(filename, 'r') as file:
        rsa_numbers = [int(line.strip()) for line in file.readlines()]

    for n in rsa_numbers:
        result = factorize_rsa_number(n)
        print(result)

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: ./rsa <file>")
        sys.exit(1)

    filename = sys.argv[1]
    main(filename)

